### ISSUE TITLE
Honors Thesis Signature

### ISSUE THREAD

**Issue by anaboccanfuso** [SCCapstone/Appstone#451]
Hi, Professor Vidal! Here is our honors thesis for you to sign. Thank you in advance!
[FlashDash_ Final Paper.pdf](https://github.com/SCCapstone/Appstone/files/11217260/FlashDash_.Final.Paper.pdf)

**Comment by josemvidal** [comment]
Here it is:

[FlashDash_.Final.Paper.pdf](https://github.com/SCCapstone/Appstone/files/11231940/FlashDash_.Final.Paper.pdf)
