### ISSUE TITLE
Credentials Exposed

### ISSUE THREAD

**Issue by csquared** [SCCapstone/Appstone#457]
https://github.com/SCCapstone/Appstone/blob/98c27844790d3456d6a0cc6ff0a795110651895d/backend/backend/settings.py#L239-L240

Hi there:
Chris from Bucketeer here. These credentials are on the public internet. I've rolled them and new ones are available in your Heroku app - please keep them private in the future!
Cheers,
Chris

**Comment by willDuggan54** [comment]
Hi Chris,

Thanks so much for taking care of that! This repo is for our school project and so we just did not realize that we were exposing our keys. We will be more careful in the future!

Thanks again,
Will
